// Minimal MCP face over the vendored communicate CLI. No fabric logic here:
// every tool is one spawn of the CLI. APPEND ONLY — order is the tools/list contract.
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { communicateCli, packageVersion } from "./paths.mjs";

const exec = promisify(execFile);
const run = async (args, timeoutMs = 120000) => (await exec(communicateCli, args, { encoding: "utf8", timeout: timeoutMs, maxBuffer: 8 * 1024 * 1024 })).stdout;
const text = (s) => ({ content: [{ type: "text", text: s || "(no output)" }] });
const fail = (e) => ({ content: [{ type: "text", text: String(e.stdout || e.stderr || e.message || e) }], isError: true });

// Handshake guidance is also available to clients that expose MCP instructions.
// Client activation is verified separately; a handshake is not a system prompt.
const INSTRUCTIONS = `HOMI supplies durable identities, native agent messaging, an explicit bus, and terminal seats. Existing communicate tool names remain compatible. Choose the namespace deliberately: homi_* tools (CLI homi) address durable identities and seats; bus_* tools (CLI homi bus) address exact registrations on a configured hub; agents_list/route/send/ask and codex_* tools (CLI homi native) use native session routes. Do not silently replace a target across these namespaces.
The user asks for an outcome in natural language; perform the necessary tool calls instead of asking them to run claim/start/spawn/send/ask commands. To create an agent and bring back its work, inspect homi_status and homi_agents, start the local daemon with homi_start if the requested work needs it, then homi_spawn in the intended project. The seat driver creates its configured tmux session as needed (default named server homi, session homi-seats); do not require manual tmux initialization or switch to an unrelated ambient server. For Claude, check the returned seat and adoption plus a live, unambiguous native route. Codex spawning does not bind its durable name to a queue: establish the exact thread belonging to the returned seat and use its verified native/bus queue and reply mechanism, without guessing from the newest transcript or shared cwd. Missing dependencies, login or unresolved routing require honest diagnosis. For a verified durable recipient, claim a per-task sender as needed and use homi_ask with the exact reply token; return the actual answer. Follow homi-core for this end-to-end procedure; stored mail or an idle screen does not complete it.
When asked to register yourself on the bus, inspect bus_status first without starting services. Use the configured hub. With no hub, local operation and a user-controlled or hosted hub are valid choices: follow stated intent, or clarify the intended scope. Do not assume any private hosted account or silently create a local broker to satisfy a shared-hub request. Local registration needs no remote invitation; a remote hub requires its scoped enrollment. Browser sign-in, Tailscale reachability and installation do not grant membership or terminal control. Never infer account ownership from names/email or hostnames.
Registration attaches the exact existing Claude socket or CODEX_THREAD_ID. If MCP lacks this context, run the equivalent CLI in the current session shell. Never guess the newest session, create a headless peer, or substitute another conversation. Named-bus registration does not also join general. General permits an unpublished exact local sender on an enrolled device to initiate to a published recipient; private buses require explicit membership. Preserve the originating hub, recipient ID and supplied reply command. bus_reply answers within the original participants and fixed 24-hour window, including human inbox messages. Keep bus dashboard fragment tokens, invites and credentials private.
Durable identity creation (homi_claim) need not launch a process; homi_spawn creates an identity and its execution. A seat is a tmux/server-scoped terminal handle, not a global identity or sandbox. Retiring a claim, stopping execution and deleting data are different. Use the recipient's native adapter when available; terminal input is explicit control and can execute commands. Seat access requires its separate grant remotely. Read-only status should not start services; homi_start is appropriate when necessary for the user's requested local work, without asking them to run it themselves.
Stored mail, runtime/queue submission and an actual reply are distinct evidence. A Codex queue receipt does not prove consumption or wake. The legacy durable ask can resolve a natural uncorrelated reply; prefer the supplied explicit reply token and do not describe fallback matches as strongly correlated. Claude's inbound gate may hold or refuse mail: report that instead of retrying blindly. HOMI supports the caller's configured providers, not universal app control. The bus dashboard, graph and human inbox remain available. See homi-core and communicate-bus for workflows; terminal/mesh profiles are optional.`;
const identityName = z.string().regex(/^[a-z0-9][a-z0-9._-]*$/);
const seconds = z.number().min(0.1).max(600);

const TOOLS = [
  { name: "agents_list", desc: "Legacy socket routing table (separate from explicit bus membership): local Claude sessions, bridged remotes, and Codex peers with status, working dir, and DESCRIPTION — each session's own chat title. Match intent against descriptions, then address by exact name.", schema: { json: z.boolean().optional().describe("machine-readable rows incl. sockets") }, argv: (a) => a.json ? ["agents", "--json"] : ["agents"] },
  { name: "whereis", desc: "Resolve an agent name to type/via/socket.", schema: { name: z.string() }, argv: (a) => ["whereis", a.name] },
  { name: "route", desc: "Send a message to any agent by name (Claude or Codex, local or bridged). The reply returns to the caller's messaging socket when one exists.", schema: { name: z.string(), message: z.string() }, argv: (a) => ["route", a.name, a.message] },
  { name: "send", desc: "Raw-inject one message into a peer socket or named peer, with optional from-name attribution.", schema: { target: z.string(), message: z.string(), as: z.string().optional() }, argv: (a) => a.as ? ["send", a.target, "--as", a.as, "--", a.message] : ["send", a.target, "--", a.message] },
  { name: "codex_queue", desc: "Enqueue a turn into an EXISTING Codex session by native name/UUID (async; the reply stays in that session). Codex CLI >= 0.151.", schema: { device: z.string(), session: z.string(), message: z.string() }, argv: (a) => ["codex", "queue", a.device, a.session, "--", a.message] },
  { name: "codex_ask", desc: "Ask a headless Codex agent synchronously (codex exec with remembered thread continuity; read-only sandbox unless auto).", schema: { device: z.string(), message: z.string(), dir: z.string().optional(), thread: z.string().optional(), fresh: z.boolean().optional(), auto: z.boolean().optional() }, argv: (a) => ["codex", "ask", a.device, ...(a.dir ? ["--dir", a.dir] : []), ...(a.thread ? ["--thread", a.thread] : []), ...(a.fresh ? ["--new"] : []), ...(a.auto ? ["--auto"] : []), "--", a.message] },
  { name: "status", desc: "Active bridges, codex peers, and wakes started by communicate on this machine.", schema: {}, argv: () => ["status"] },
  { name: "ask", desc: "Ask any agent by name and WAIT for the reply. Works on Claude sessions/peers and on local Codex sessions (by native thread name). The delivered question carries an in-band [reply-to ...] block teaching the receiver exactly how to answer, so nothing needs to be installed on their side.", schema: { name: z.string(), message: z.string(), timeout: z.number().optional().describe("seconds to wait (default 90)") }, argv: (a) => ["ask", a.name, "--timeout", String(a.timeout ?? 90), "--", a.message], timeoutMs: (a) => ((a.timeout ?? 90) + 30) * 1000 },
  { name: "card_set", desc: "Set a legacy socket-roster card (Claude sidecar identity). Cards beat chat titles in that roster and survive resumes. For explicit bus registrations, use bus_register with description instead.", schema: { name: z.string().describe("agent name, or 'self'"), what: z.string().optional(), ask_me_for: z.string().optional() }, argv: (a) => ["card", "set", a.name, ...(a.what ? ["--what", a.what] : []), ...(a.ask_me_for ? ["--ask-me-for", a.ask_me_for] : [])] },
  { name: "bus_register", desc: "Publish this existing agent on general for discovery and incoming requests, or explicitly join a private named bus. Defaults to self/general; a named bus joins only that bus. Resolves the current Claude socket or CODEX_THREAD_ID, never creates a replacement agent. If identity is unavailable through MCP, run the equivalent CLI inside the session shell.", schema: { target: z.string().optional().describe("self (default), or exact local agent name"), bus: z.string().optional(), name: z.string().optional().describe("bus display alias"), session: z.string().optional().describe("verified existing session ID; never guess"), kind: z.enum(["codex", "claude"]).optional(), description: z.string().optional() }, argv: (a) => ["bus", "register", a.target ?? "self", "--bus", a.bus ?? "general", ...(a.name ? ["--name", a.name] : []), ...(a.session ? ["--session", a.session] : []), ...(a.kind ? ["--kind", a.kind] : []), ...(a.description ? ["--description", a.description] : [])] },
  { name: "bus_list", desc: "List buses visible to this device on its configured broker. General is local to that broker, not an internet-wide directory.", schema: {}, argv: () => ["bus", "list", "--json"] },
  { name: "bus_agents", desc: "List registered agents and their membership/status on the configured bus broker. Codex queueable means an exact existing thread can receive queued turns; it does not prove an active agent.", schema: { bus: z.string().optional() }, argv: (a) => ["bus", "agents", ...(a.bus ? ["--bus", a.bus] : []), "--json"] },
  { name: "bus_leave", desc: "Remove this session's membership in one bus.", schema: { target: z.string().optional().describe("self (default), or registered agent ID"), bus: z.string().optional() }, argv: (a) => ["bus", "leave", a.target ?? "self", "--bus", a.bus ?? "general"] },
  { name: "bus_send", desc: "Initiate a conversation with a published recipient. General permits any exact local agent on an enrolled device without publishing the sender; private buses require both agents to join. Use bus_reply for answers. Returns a receipt, not an agent answer.", schema: { target: z.string(), message: z.string(), bus: z.string().optional(), from: z.string().optional().describe("self (default), or sender registration ID owned by this device"), hub: z.string().optional().describe("connected broker origin, or local; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "send", a.target, "--bus", a.bus ?? "general", "--from", a.from ?? "self", "--", a.message] },
  { name: "bus_receipt", desc: "Inspect delivery status for a bus message receipt. Distinguishes gateway acceptance from endpoint delivery or Codex queueing; does not assert an answer.", schema: { id: z.string(), hub: z.string().optional().describe("connected broker origin, or local; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "receipt", a.id] },
  { name: "bus_status", desc: "Inspect this device's configured broker and worker without starting services. configured:false means no hub is selected; local or explicitly enrolled remote operation can be chosen.", schema: {}, argv: () => ["bus", "status", "--json", "--no-start"] },
  { name: "bus_dashboard", desc: "Return an authenticated browser URL for the bus interface. Treat its fragment token as a credential; show it only to the requesting user.", schema: {}, argv: () => ["bus", "dashboard"] },
  { name: "bus_create", desc: "Create a named bus on the locally administered broker. Remote invited devices cannot create arbitrary buses; ask the broker owner for membership.", schema: { name: z.string() }, argv: (a) => ["bus", "create", a.name] },
  { name: "bus_device", desc: "Refresh this installation's device metadata or display name on the selected broker. Stable device identity and administrator-assigned account ownership do not change. Only this machine's hostname, platform, and optional Tailscale Self names are collected.", schema: { name: z.string().optional().describe("new display label for this device"), hub: z.string().optional().describe("connected broker origin, or local; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "device", ...(a.name ? ["--name", a.name] : [])] },
  { name: "bus_reply", desc: "Reply to a message received by this exact agent, within its original participants and bus. The conversation expires 24 hours after initiation; replies do not extend it. This permits replies to unpublished general senders without publishing them.", schema: { id: z.string().describe("received message ID"), message: z.string(), from: z.string().optional().describe("self (default), or original recipient registration ID owned by this device"), hub: z.string().optional().describe("originating connected broker; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "reply", a.id, "--from", a.from ?? "self", "--", a.message] },

  // Durable HOMI tools append to the original native/bus list. Every operation
  // delegates to the existing CLI and daemon; no second mailbox or resolver.
  { name: "homi_status", desc: "Inspect the durable daemon, identities and measured execution state. Does not start it.", schema: {}, argv: () => ["homi", "status", "--json"] },
  { name: "homi_start", desc: "Start the existing local durable HOMI daemon when requested. Does not enroll a remote device or spawn an agent.", schema: {}, argv: () => ["homi", "start"] },
  { name: "homi_agents", desc: "List durable identities, mail and current execution bindings; separate from native sessions and bus registrations.", schema: {}, argv: () => ["homi", "agents", "--json"] },
  { name: "homi_claim", desc: "Create a durable address/mailbox without starting an agent. Existing claims are retained.", schema: { name: identityName, cwd: z.string().optional() }, argv: (a) => ["homi", "claim", a.name, ...(a.cwd ? ["--cwd", a.cwd] : [])] },
  { name: "homi_release", desc: "Release a durable identity's active claim. This is not execution termination or deletion of its saved mail.", schema: { name: identityName }, argv: (a) => ["homi", "release", a.name] },
  { name: "homi_send", desc: "Store/route mail to a durable identity (optionally name@device). A successful route is not an agent answer.", schema: { target: z.string(), message: z.string(), from: identityName }, argv: (a) => ["homi", "send", a.target, "--from", a.from, "--", a.message] },
  { name: "homi_ask", desc: "Send to a durable identity and wait for a reply. Prefer the supplied explicit token; the legacy natural-reply fallback remains best-effort.", schema: { target: z.string(), message: z.string(), from: identityName, timeout: seconds.optional() }, argv: (a) => ["homi", "ask", a.target, "--from", a.from, "--timeout", String(a.timeout ?? 90), "--json", "--", a.message], timeoutMs: (a) => ((a.timeout ?? 90) + 30) * 1000 },
  { name: "homi_reply", desc: "Answer using the exact durable request's reply token and your claimed identity.", schema: { token: z.string(), message: z.string(), from: identityName }, argv: (a) => ["homi", "reply", a.token, "--from", a.from, "--", a.message] },
  { name: "homi_inbox", desc: "Read the saved JSONL mailbox of a local durable identity. Reading does not claim execution or completion.", schema: { name: identityName }, argv: (a) => ["homi", "inbox", a.name] },
  { name: "homi_wait", desc: "Wait for stored mail at a durable local identity. This does not start a sleeping model process.", schema: { name: identityName, timeout: seconds.optional() }, argv: (a) => ["homi", "wait", a.name, "--timeout", String(a.timeout ?? 60), "--json"], timeoutMs: (a) => ((a.timeout ?? 60) + 30) * 1000 },
  { name: "homi_spawn", desc: "Create a durable identity and start the selected Claude/Codex execution in a tmux seat using existing spawn behavior. Uses configured provider authentication.", schema: { name: identityName, cli: z.enum(["claude", "codex"]), cwd: z.string().optional() }, argv: (a) => ["homi", "spawn", a.name, "--cli", a.cli, ...(a.cwd ? ["--cwd", a.cwd] : []), "--json"] },
  { name: "homi_restart", desc: "Restart an existing supervised identity using its recorded command/cwd. Process restart is not proof of restored conversation state.", schema: { name: identityName }, argv: (a) => ["homi", "restart", a.name] },
  { name: "homi_seats", desc: "List terminal seats on the daemon's configured tmux server.", schema: {}, argv: () => ["homi", "seat", "ls"] },
  { name: "homi_seat_spawn", desc: "Explicitly run a command in a new terminal seat; remote creation needs an existing link with seat permission. An ordinary seat is not sandboxed.", schema: { command: z.string(), cwd: z.string().optional(), device: z.string().optional() }, argv: (a) => ["homi", "seat", "spawn", ...(a.cwd ? ["--cwd", a.cwd] : []), ...(a.device ? ["--device", a.device] : []), a.command] },
  { name: "homi_seat_send", desc: "Explicitly submit terminal input to a seat. This can execute shell commands; it is not mailbox delivery.", schema: { seat: z.string(), input: z.string() }, argv: (a) => ["homi", "seat", "send", a.seat, a.input] },
  { name: "homi_seat_read", desc: "Read a terminal screen and observed state; screen text is not a correlated agent answer.", schema: { seat: z.string(), lines: z.number().int().min(1).max(2000).optional() }, argv: (a) => ["homi", "seat", "read", a.seat, "--lines", String(a.lines ?? 40)] },
  { name: "homi_seat_state", desc: "Observe a seat's terminal state. Unknown means the driver could not establish its state, not that it died.", schema: { seat: z.string() }, argv: (a) => ["homi", "seat", "state", a.seat] },
  { name: "homi_seat_bind", desc: "Bind a seat to a claimed identity. Mail relay is a separate explicit opt-in, not implied by binding.", schema: { seat: z.string(), name: identityName, relay: z.boolean().optional() }, argv: (a) => ["homi", "seat", "bind", a.seat, a.name, ...(a.relay ? ["--relay"] : [])] },
  { name: "homi_seat_interrupt", desc: "Send Escape to the selected seat using the existing driver. The identity and saved mail remain.", schema: { seat: z.string() }, argv: (a) => ["homi", "seat", "interrupt", a.seat] },
  { name: "homi_seat_kill", desc: "Terminate the selected terminal pane when explicitly requested. This does not delete its durable identity or saved state.", schema: { seat: z.string() }, argv: (a) => ["homi", "seat", "kill", a.seat] },

];

export async function runServe() {
  const server = new McpServer({ name: "communicate", version: packageVersion }, { instructions: INSTRUCTIONS });
  for (const t of TOOLS) {
    server.registerTool(t.name, { description: t.desc, inputSchema: t.schema }, async (args) => {
      const a = args ?? {};
      try { return text(await run(t.argv(a), t.timeoutMs ? t.timeoutMs(a) : undefined)); } catch (e) { return fail(e); }
    });
  }
  await server.connect(new StdioServerTransport());
}
